package io.github.kdroidfilter.webview.wry

// The UniFFI bindings are now generated by IronCoreLabs/uniffi-bindgen-java as pure-FFM Java
// (package uniffi.composewebview_wry), replacing the gobleyUniffi JNA Kotlin codegen so the
// library works in GraalVM native-image. These aliases let the existing same-package references
// to WebViewCookie/Rgba/etc. resolve to the generated Java types without touching every usage.

public typealias WebViewCookie = uniffi.composewebview_wry.WebViewCookie
public typealias HttpHeader = uniffi.composewebview_wry.HttpHeader
public typealias Rgba = uniffi.composewebview_wry.Rgba
public typealias CookieSameSite = uniffi.composewebview_wry.CookieSameSite
public typealias NavigationHandler = uniffi.composewebview_wry.NavigationHandler
public typealias JavaScriptCallback = uniffi.composewebview_wry.JavaScriptCallback
public typealias NativeLogger = uniffi.composewebview_wry.NativeLogger
public typealias WebViewException = uniffi.composewebview_wry.WebViewException
